#!/usr/bin/env bash

exec 3>&1 &>/dev/null

if [ "$DPKG_MAINTSCRIPT_ARCH" == "iphoneos-arm64" ]; then
    DPKG_ROOT="/var/jb"
fi

SERV_AGENT="$DPKG_ROOT/Library/LaunchDaemons/com.82flex.trollvnc.plist"

if [ -f "$SERV_AGENT" ]; then
    launchctl unload "$SERV_AGENT" || true
else
    launchctl remove system/com.82flex.trollvnc || true
fi

sleep 2

if [ -f "$SERV_AGENT" ]; then
    launchctl load -w -F "$SERV_AGENT" || true
fi

STATS_FILE="$DPKG_ROOT/usr/share/trollvnc/webclients/stats.js"
if [ -f "$STATS_FILE" ]; then
    chown mobile:mobile "$STATS_FILE" || true
    chmod 666 "$STATS_FILE" || true
fi

exit 0